apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-model
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iris-model
  template:
    metadata:
      labels:
        app: iris-model
    spec:
      containers:
      - name: iris-model
        image: iris-model:v1
        ports:
        - containerPort: 5000
